In [3]:
list_two = list(range(1,4))
list_three = list(range(1,4))
list_sum = []

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])

print(list_sum)

[2, 12, 36]


In [4]:
import numpy as np

array_two = np.arange(1, 4) ** 2
array_three =np.arange(1, 4) ** 3
print(array_two + array_three)

[ 2 12 36]


In [9]:
sample_array = np.array ([1, 2, 3])

In [10]:
np.power(sample_array, 4)

array([ 1, 16, 81], dtype=int32)

In [11]:
np.negative(sample_array)

array([-1, -2, -3])

In [12]:
np.exp(sample_array)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [13]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229])

In [14]:
np.sin(sample_array)

array([0.84147098, 0.90929743, 0.14112001])