In [17]:
# an N dimensional array is defined by the shape and the item it's composed of
# the advantage of all items being the same data type means they all have
# the same memory size making it easier to compute array size
import numpy as np
x = np.arange(3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x,y,z], dtype=np.int16)
print(multi_array)
print(multi_array.shape)
multi_array[1, 2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


5

In [18]:
print(multi_array.dtype)

int16
