In [1]:
import numpy as np

x = np.arange(1, 10)
print(x)


[1 2 3 4 5 6 7 8 9]


In [5]:
print(x[2:7:2])
print(x[:7:2])
print(x[2:])

[3 5 7]
[1 3 5 7]
[3 4 5 6 7 8 9]


In [7]:
# Before we can slice through multidimensional arrays, we need to reshape them
y = np.arange(9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
