<a href="https://colab.research.google.com/github/Kowus/k3ye/blob/master/numpy_revisions/47_multidimensional_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
x = np.arange(18).reshape(3, 2, 3)
print (x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [17]:
# x[1, 0:, 0:]
# x[1, :, :]
# x[1, ...]
x[1, :2, :3:2]

array([[ 6,  8],
       [ 9, 11]])

In [21]:
comparison_operation = x > 5
# print(comparison_operation)
# x[comparison_operation]
x[x>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [23]:
# x.max()
x.min()

0