<a href="https://colab.research.google.com/github/Kowus/k3ye/blob/master/numpy_revisions/48_manipulating_array_shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
ravelled_array = x.ravel()
print(ravelled_array)

[0 1 2 3 4 5 6 7 8]


In [18]:
flattened_array = x.flatten()
print(flattened_array)
# How different is flatten from ravel?
# flatten creates a copy and requires
# additional memory.
# ravel returns a view of the original array
# if I modify anything in a ravelled array,
# it gets modified in the original copy
# eg.
# ravelled_array[3] = 789
flattened_array[3] = 789
print(flattened_array, x)

[0 1 2 3 4 5 6 7 8]
[  0   1   2 789   4   5   6   7   8] [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
y = np.arange(9)
y.shape=[3,3]
print(y.T)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [21]:
print(np.resize(y, (6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [26]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [31]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [32]:
np.random.rand(4,4)

array([[0.28979268, 0.50909016, 0.75477422, 0.96298035],
       [0.89854616, 0.46938006, 0.55059873, 0.00488756],
       [0.93356785, 0.97328818, 0.2188116 , 0.73655154],
       [0.05536121, 0.18246955, 0.29395829, 0.40240104]])