<a href="https://colab.research.google.com/github/Kowus/k3ye/blob/master/numpy_revisions/49_matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [6]:
mat_a = np.matrix([0,3,5,5,5,2]).reshape(2,3)
mat_a

matrix([[0, 3, 5],
        [5, 5, 2]])

In [7]:
mat_b = np.matrix([3,4,3,-2,4,-2]).reshape(3,2)
mat_b

matrix([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [12]:
# mat_a * mat_b
# product = np.matmul(mat_a,mat_b)
# product
mat_a @ mat_b

matrix([[ 29, -16],
        [ 38,   6]])