<a href="https://colab.research.google.com/github/Kowus/k3ye/blob/master/50_stacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
x = np.arange(4).reshape(2,2)
print(x)

[[0 1]
 [2 3]]


In [10]:
# y = np.arange(4).reshape(2,2)
y = x * 2
print(y)

[[0 2]
 [4 6]]


In [11]:
z = np.hstack((x,y))
print(z)

[[0 1 0 2]
 [2 3 4 6]]


In [12]:
a = np.vstack((x,y))
print(a)

[[0 1]
 [2 3]
 [0 2]
 [4 6]]


In [13]:
w = np.concatenate((x, y), axis=1)
v = np.concatenate((x, y), axis=0)

# print(w)
print(z == w,"\n\n", a == v)

[[ True  True  True  True]
 [ True  True  True  True]] 

 [[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]


In [14]:
depth_stack = np.dstack((x,y))
print(depth_stack)

[[[0 0]
  [1 2]]

 [[2 4]
  [3 6]]]


In [17]:
depth_stack[1, 1, 1]

6

In [20]:
colstack = np.column_stack((x,y))
print(colstack)
colstack == z

[[0 1 0 2]
 [2 3 4 6]]


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
row_stack = np.row_stack((x,y))
print(row_stack)
a == row_stack

[[0 1]
 [2 3]
 [0 2]
 [4 6]]


array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])